server:
  port: 8085
  servlet:
    context-path: /forum

# 应用名称
spring:
  application:
    name: knowledgelink-forum
  cloud:
    nacos:
      server-addr: 175.27.129.187:8848
      discovery:
        enabled: false
      config:
        enabled: false
  elasticsearch:
    uris: http://101.42.227.93:9200
    username: elastic
    password: 133017
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.227.93:3306/kl_forum?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 133017
    hikari:
      max-lifetime: 540000
      idle-timeout: 300000
      keepalive-time: 120000
      connection-timeout: 30000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 20
  data:
    redis:
      host: 101.42.227.93
      port: 6379
      password: 133017
      database: 1
      timeout: 3000ms
      connect-timeout: 3000ms
      lettuce:
        pool:
          min-idle: 8
          max-idle: 8
          max-active: 20
          max-wait: 2000ms
          time-between-eviction-runs: 30s
  servlet:
    # 文件上传配置信息
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB  #整体文件最大请求限制

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

dashscope:
  image:
    apiKey: sk-98ff5ef4ab644997af365d6598bc36c3
    baseUrl: https://dashscope.aliyuncs.com/api/v1
    model: qwen-image-2.0-pro
    n: 1
    size: 1664*928
    negativePrompt: ""
    promptExtend: true
    watermark: false

# 日志配置
logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com.github.forum: debug
  file:
    name: logs/KnowledgeLink-forum.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 360
      total-size-cap: 1GB
      clean-history-on-start: false

tencent:
  cos:
    secret-id: AKIDwPipmXegXFyWt56xc6RbaO0Umt22rUxG
    secret-key: GLFg086sSo25xZ2A8ygBTYTCj5HMH2rh
    region: ap-nanjing
    bucket-name: ningning-1402906498
    url: https://ningning-1402906498.cos.ap-nanjing.myqcloud.com

forum:
  es:
    post-index: forum_post
  recommend:
    weight:
      like: 2.0
      collect: 3.0
      page-view: 0.10
      comment: 1.20
      hot-like: 1.50
      hot-collect: 2.00
      behavior-score: 0.55
      hot-score: 0.35
      fresh-score: 0.10
      fresh-decay-hours: 72.0

remote:
  user-base-url: http://175.27.129.187:8086/user

jwt:
  secret: knowledge-link-local-jwt-secret-2026-very-long-key


