#数据库连接池配置
spring:
  application:
    name: learning_exchange_platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learning_exchange_platform
    username: root
    password: Lcd200501060106
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
    # 重要：确保静态资源不拦截 WebSocket 路径
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

  # 禁用 Spring MVC 对 WebSocket 路径的处理
  server:
    servlet:
      context-path: /

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG